export const categoryOptions = [
    "Baby",
    "Bread & Bakery",
    "Breakfast & Cereal",
    "Canned Goods & Soups",
    "Condiments/Spices & Bake",
    "Cookies, Snacks & Candy",
    "Dairy & Eggs",
    "Frozen Foods",
    "Fruits & Vegetables",
    "Grains, Pasta & Sides",
    "Meat & Seafood",
    "Pet Care",
    "Other",
];
